import { Artwork, ArtworkImage } from "@/types/artwork";

// Placeholder data used only when Supabase env vars aren't configured yet,
// so the site is viewable during setup. Shape matches the real DB schema.
export const mockArtworks: Artwork[] = [
  {
    id: "1",
    title: "Quiet Harbor",
    year: "2023",
    medium: "Oil on canvas",
    dimensions: "60 x 90 cm",
    status: "available",
    theme: "landscape",
    description: "A still morning at the harbor, light breaking over calm water.",
    inspiration: "A dawn walk along the coast during a residency.",
    process: "Layered glazes over a limited palette to hold the early light.",
    gradient_bg: "linear-gradient(135deg, #2c3e50, #4ca1af)",
    image_url: "https://picsum.photos/seed/harbor1/1200/800",
    sort_order: 1,
    created_at: new Date().toISOString(),
  },
  {
    id: "2",
    title: "Portrait in Ochre",
    year: "2022",
    medium: "Acrylic on board",
    dimensions: "50 x 70 cm",
    status: "sold",
    theme: "portrait",
    description: "A study of warmth and shadow in a single sitting.",
    inspiration: "Late afternoon light through a studio window.",
    process: "Blocked in with ochre and burnt sienna, then refined over three sessions.",
    gradient_bg: "linear-gradient(135deg, #d38312, #a83279)",
    image_url: "https://picsum.photos/seed/ochre2/900/1200",
    sort_order: 2,
    created_at: new Date().toISOString(),
  },
  {
    id: "3",
    title: "Fields at Dusk",
    year: "2024",
    medium: "Oil on linen",
    dimensions: "80 x 120 cm",
    status: "available",
    theme: "landscape",
    description: "Wide open fields as the last light fades to violet.",
    inspiration: "Driving home through farmland at the end of summer.",
    process: "Painted alla prima to capture the fast-changing light.",
    gradient_bg: "linear-gradient(135deg, #41295a, #2F0743)",
    image_url: "https://picsum.photos/seed/fields3/1200/800",
    sort_order: 3,
    created_at: new Date().toISOString(),
  },
  {
    id: "4",
    title: "Self, Unfinished",
    year: "2024",
    medium: "Charcoal and oil on paper",
    dimensions: "40 x 55 cm",
    status: "in-progress",
    theme: "portrait",
    description: "An ongoing study, left deliberately incomplete.",
    inspiration: "Returning to the same mirror sketch over several months.",
    process: "Charcoal underdrawing left visible beneath sparse oil passages.",
    gradient_bg: "linear-gradient(135deg, #232526, #414345)",
    image_url: "https://picsum.photos/seed/selfport4/900/1200",
    sort_order: 4,
    created_at: new Date().toISOString(),
  },
  {
    id: "5",
    title: "River Bend",
    year: "2021",
    medium: "Watercolor on paper",
    dimensions: "45 x 65 cm",
    status: "available",
    theme: "landscape",
    description: "A slow river curving through late autumn trees.",
    inspiration: "A recurring view from a footbridge near the studio.",
    process: "Wet-on-wet washes for the water, dry brush for the tree line.",
    gradient_bg: "linear-gradient(135deg, #134e5e, #71b280)",
    image_url: "https://picsum.photos/seed/river5/1200/800",
    sort_order: 5,
    created_at: new Date().toISOString(),
  },
  {
    id: "6",
    title: "Woman with Red Shawl",
    year: "2020",
    medium: "Oil on canvas",
    dimensions: "55 x 75 cm",
    status: "sold",
    theme: "portrait",
    description: "A commissioned portrait exploring color against a muted ground.",
    inspiration: "The sitter's own choice of a bright red shawl against a grey day.",
    process: "Built up in thin transparent layers to keep the red luminous.",
    gradient_bg: "linear-gradient(135deg, #8E0E00, #1F1C18)",
    image_url: "https://picsum.photos/seed/shawl6/900/1200",
    sort_order: 6,
    created_at: new Date().toISOString(),
  },
];

export const mockArtworkImages: ArtworkImage[] = mockArtworks.flatMap((a) => [
  {
    id: `${a.id}-img-2`,
    artwork_id: a.id,
    url: `https://picsum.photos/seed/${a.id}-detail1/1000/1000`,
    filename: "detail-1.jpg",
    caption: "Detail",
    sort_order: 1,
    created_at: new Date().toISOString(),
  },
  {
    id: `${a.id}-img-3`,
    artwork_id: a.id,
    url: `https://picsum.photos/seed/${a.id}-detail2/1000/1000`,
    filename: "in-studio.jpg",
    caption: "In the studio",
    sort_order: 2,
    created_at: new Date().toISOString(),
  },
]);
